//! Terminal adapter: owns the event loop and translates crossterm key events
//! into the browser shaped events the keybind expressions are written against.

// The model layers are ported whole (cell editing, row deletion, foreign key
// lookups, message history); the commands that drive them land in the next
// pass. Drop this once they are wired up.
#![allow(dead_code)]

mod app;
mod commands;
mod config;
mod db;
mod keybinds;
mod picker;
mod state;
mod table;
mod ui;

use crossterm::event::{Event, EventStream, KeyCode, KeyEventKind, KeyModifiers};
use futures::StreamExt;
use std::time::Duration;
use tokio::sync::mpsc;

use app::App;
use keybinds::{KeyEvent, KeyOutcome};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let (tx, mut rx) = mpsc::unbounded_channel();
    let mut app = App::new(tx.clone());

    // Replaces `pnpm gen-commands` / `pnpm gen-docs`: the registry and the
    // config struct are the source of truth.
    if std::env::args().any(|arg| arg == "--commands") {
        print!("{}", commands_markdown(&app));
        return Ok(());
    }

    if std::env::args().any(|arg| arg == "--config-schema") {
        let schema = schemars::schema_for!(config::Configuration);
        println!("{}", serde_json::to_string_pretty(&schema)?);
        return Ok(());
    }

    match std::env::args().nth(1) {
        Some(url) => app.set_active_url(&url),
        None => app.connect(),
    }

    // Kept alive for the duration of the run so the config stays watched.
    let _watcher = config::watch(tx.clone());

    let mut terminal = ratatui::init();
    let mut events = EventStream::new();

    while !app.should_quit {
        terminal.draw(|frame| ui::draw(frame, &mut app))?;

        tokio::select! {
            event = events.next() => match event {
                Some(Ok(event)) => on_event(&mut app, event),
                Some(Err(error)) => return Err(error.into()),
                None => break,
            },
            msg = rx.recv() => match msg {
                Some(msg) => app.on_msg(msg),
                None => break,
            },
            // Redraw periodically so message toasts expire on time.
            _ = tokio::time::sleep(Duration::from_millis(250)) => {}
        }

        app.drain_pending();
    }

    ratatui::restore();
    app.state.save();
    Ok(())
}

/// The command reference in `config/commands.md`.
fn commands_markdown(app: &App) -> String {
    let binds: std::collections::HashMap<String, String> = app
        .keybinds
        .default_keybinds()
        .into_iter()
        .map(|k| (k.command, k.bind))
        .collect();

    let mut out = String::new();
    out.push_str("# Commands\n\n");
    out.push_str("This file is auto-generated by `tablezz --commands`. Do not edit manually.\n\n");
    out.push_str("| Command | Description | Arguments | Keybind |\n|---|---|---|---|\n");

    for (name, command) in app.commands.all(&app.config.command_aliases) {
        let description = command.description.clone().unwrap_or_default();
        let args = command.args_hint();
        let bind = binds
            .get(&name)
            .map(|b| format!("`{}`", b.replace('|', "\\|")))
            .unwrap_or_else(|| "-".to_string());

        out.push_str(&format!("| {name} | {description} | {args} | {bind} |\n"));
    }

    out
}

fn on_event(app: &mut App, event: Event) {
    let Event::Key(key) = event else { return };

    if key.kind != KeyEventKind::Press {
        return;
    }

    let Some(mapped) = to_key_event(&key) else {
        return;
    };

    match app.keybinds.handle_key(&mapped, app.input_focused()) {
        KeyOutcome::Triggered(command) => app.trigger_command(&command),
        KeyOutcome::Consumed => {}
        // Nothing claimed the key, so a focused text input gets it — the
        // equivalent of the browser letting the event reach the <input>.
        KeyOutcome::Ignored => feed_input(app, &key),
    }
}

/// Map a crossterm key to the `KeyboardEvent` shape (`key` + `code`) the
/// keybind checker compares against.
fn to_key_event(key: &crossterm::event::KeyEvent) -> Option<KeyEvent> {
    let named = |name: &str| Some((name.to_string(), name.to_string()));

    let (key_name, code) = match key.code {
        KeyCode::Char(' ') => Some((" ".to_string(), "Space".to_string())),
        KeyCode::Char(char) => Some((char.to_string(), String::new())),
        KeyCode::Enter => named("Enter"),
        KeyCode::Tab | KeyCode::BackTab => named("Tab"),
        KeyCode::Backspace => named("Backspace"),
        KeyCode::Delete => named("Delete"),
        KeyCode::Insert => named("Insert"),
        KeyCode::Esc => named("Escape"),
        KeyCode::Up => named("ArrowUp"),
        KeyCode::Down => named("ArrowDown"),
        KeyCode::Left => named("ArrowLeft"),
        KeyCode::Right => named("ArrowRight"),
        KeyCode::Home => named("Home"),
        KeyCode::End => named("End"),
        KeyCode::PageUp => named("PageUp"),
        KeyCode::PageDown => named("PageDown"),
        KeyCode::F(n) => Some((format!("F{n}"), format!("F{n}"))),
        _ => None,
    }?;

    Some(KeyEvent {
        ctrl_key: key.modifiers.contains(KeyModifiers::CONTROL),
        alt_key: key.modifiers.contains(KeyModifiers::ALT),
        meta_key: key.modifiers.contains(KeyModifiers::SUPER),
        key: key_name,
        code,
    })
}

fn feed_input(app: &mut App, key: &crossterm::event::KeyEvent) {
    // Control/Alt chords are keybind territory, never text.
    let is_text = !key
        .modifiers
        .intersects(KeyModifiers::CONTROL | KeyModifiers::ALT | KeyModifiers::SUPER);

    if let Some(line) = app.command_line.as_mut() {
        match key.code {
            KeyCode::Char(char) if is_text => line.insert(char),
            KeyCode::Backspace => line.backspace(),
            KeyCode::Delete => line.delete(),
            KeyCode::Left => line.move_left(),
            KeyCode::Right => line.move_right(),
            KeyCode::Home => line.move_home(),
            KeyCode::End => line.move_end(),
            _ => {}
        }
        return;
    }

    if let Some(picker) = app.picker.as_mut() {
        let mut term = picker.search_term.clone();
        match key.code {
            KeyCode::Char(char) if is_text => term.push(char),
            KeyCode::Backspace => {
                term.pop();
            }
            _ => return,
        }
        picker.set_search_term(term);
    }
}
